apiVersion: apps/v1
kind: Deployment
metadata:
  name: vald-ingress-filter
  labels:
    app: vald-ingress-filter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vald-ingress-filter
  template:
    metadata:
      labels:
        app: vald-ingress-filter
    spec:
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        fsGroup: 65532
      containers:
        - name: vald-ingress-filter
          image: vdaas/vald-ingress-filter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 8082
